import { analyzeFanout, sourceDomain } from "./fanout-analysis.mjs";
import { compareFanoutRuns, comparisonCsv } from "./fanout-comparison.mjs";
import { clearSavedRuns, deleteSavedRun, loadSavedRuns, saveRun } from "./fanout-history.mjs";

type ModelledQuery={query:string;intent:string;reason:string};
type Source={url:string;title:string};
type SearchAction={id:string;queries:string[];sources:Source[];sourceScope:string};
type Usage={inputTokens:number;outputTokens:number;searchActionCount:number;searchQueryCount:number;estimatedCostUsd:number;estimatedCostUsdMaximum?:number;pricingBasis:string;pricingCheckedAt:string};
type Quota={limit:number;used:number;remaining:number;resetAt:string};
type FanoutResult={keyword:string;language:"en"|"de";country:string|null;queries:(ModelledQuery|string)[];sources?:Source[];searchActions?:SearchAction[];searchActionCount?:number;providerResponseStatus?:string;sourceEvidenceScope?:string;storageNotice?:string;usage?:Usage;modelId:string;providerId:string;generatedAt:string;evidenceStatus:string;notice:string;quota?:Quota};
type HistoryEntry={id:string;savedAt:number;expiresAt:number;result:FanoutResult};

const countryNames:Record<string,string>={DE:"Germany",US:"United States",GB:"United Kingdom",AT:"Austria",CH:"Switzerland",FR:"France",ES:"Spain",IT:"Italy",NL:"Netherlands"};
const queryText=(item:ModelledQuery|string)=>typeof item==="string"?item:item.query;

for(const root of document.querySelectorAll<HTMLElement>("[data-fanout-planner]")){
  const form=root.querySelector<HTMLFormElement>("[data-planner-form]")!,keyword=root.querySelector<HTMLInputElement>("input[name='keyword']")!,count=root.querySelector<HTMLOutputElement>("[data-keyword-count]")!,status=root.querySelector<HTMLElement>("[data-form-status]")!,quotaStatus=root.querySelector<HTMLElement>("[data-quota-status]")!,availability=root.querySelector<HTMLElement>("[data-mode-availability]")!;
  const dialog=root.querySelector<HTMLDialogElement>("[data-result-dialog]")!,loadingDialog=root.querySelector<HTMLDialogElement>("[data-loading-dialog]")!,comparisonDialog=root.querySelector<HTMLDialogElement>("[data-comparison-dialog]")!,loadingSeconds=root.querySelector<HTMLElement>("[data-loading-seconds]")!,loadingSteps=[...root.querySelectorAll<HTMLElement>("[data-loading-step]")];
  const historyList=root.querySelector<HTMLOListElement>("[data-history-list]")!,historyEmpty=root.querySelector<HTMLElement>("[data-history-empty]")!,historyTools=root.querySelector<HTMLElement>("[data-history-tools]")!,selectedCount=root.querySelector<HTMLElement>("[data-selected-count]")!,clearHistory=root.querySelector<HTMLButtonElement>("[data-clear-history]")!,compareRuns=root.querySelector<HTMLButtonElement>("[data-compare-runs]")!,exportRunsJson=root.querySelector<HTMLButtonElement>("[data-export-runs-json]")!,exportRunsCsv=root.querySelector<HTMLButtonElement>("[data-export-runs-csv]")!,saveResult=root.querySelector<HTMLButtonElement>("[data-save-result]")!;
  const submit=form.querySelector<HTMLButtonElement>("button[type='submit']")!,nativePicker=root.querySelector<HTMLFieldSetElement>("[data-native-picker]")!,modelledPicker=root.querySelector<HTMLFieldSetElement>("[data-modelled-picker]")!;
  let turnstileToken="",widgetId:string|number|undefined,lastResult:FanoutResult|undefined,loadingTimer:number|undefined,clearResetTimer:number|undefined,historyEntries:HistoryEntry[]=[];
  const selectedIds=new Set<string>(),locale=root.dataset.locale==="de"?"de":"en";
  const ui=locale==="de"?{save:"Auf diesem Gerät speichern",saved:"Gespeichert",open:"Ergebnis öffnen",remove:"Löschen",select:"Zum Vergleich auswählen",empty:"Noch keine Ergebnisse gespeichert.",historyError:"Die lokale Historie ist in diesem Browser nicht verfügbar.",saveError:"Das Ergebnis konnte nicht lokal gespeichert werden.",clear:"Alle löschen",clearConfirm:"Wirklich alle löschen?",globalLimit:"Das kostenlose Gesamtkontingent der Website ist für heute aufgebraucht.",budgetLimit:"Das kostenlose Kostenbudget ist vorübergehend aufgebraucht.",globalSources:"Weitere Quellen dieses Laufs",globalSourceNote:"Diese Quellen wurden in der Antwort zitiert, aber nicht querygenau übermittelt.",exactSources:"Für diese Query übermittelte Quellen",actionSources:"Gemeinsam für diese Suchaktion übermittelte Quellen",themesEmpty:"Keine wiederkehrenden Wörter",geminiSaved:"Google-Suchergebnisse werden nicht gespeichert; Query-Strings und Laufdaten bleiben lokal."}:{save:"Save on this device",saved:"Saved",open:"Open result",remove:"Delete",select:"Select for comparison",empty:"No saved results yet.",historyError:"Local history is not available in this browser.",saveError:"The result could not be saved locally.",clear:"Clear all",clearConfirm:"Clear every saved run?",globalLimit:"The site's free daily allowance has been used.",budgetLimit:"The free cost budget is temporarily unavailable.",globalSources:"Other sources from this run",globalSourceNote:"These sources were cited in the response but were not transmitted with an exact query link.",exactSources:"Sources transmitted for this query",actionSources:"Sources shared by this search action",themesEmpty:"No recurring words",geminiSaved:"Google Grounded Results are not saved; query strings and run metadata stay local."};
  const mode=()=>String(new FormData(form).get("mode")??"native"),modeEnabled=(value:string)=>value==="native"?root.dataset.nativeEnabled==="true":root.dataset.modelledEnabled==="true";
  const updateCount=()=>count.textContent=`${[...keyword.value.normalize("NFC")].length} / 60`;
  const updateMode=()=>{const native=mode()==="native";nativePicker.hidden=!native;modelledPicker.hidden=native;nativePicker.querySelectorAll<HTMLInputElement>("input").forEach(input=>input.disabled=!native);modelledPicker.querySelectorAll<HTMLInputElement>("input").forEach(input=>input.disabled=native);availability.hidden=modeEnabled(mode());submit.disabled=!modeEnabled(mode())};
  keyword.addEventListener("input",updateCount);updateCount();form.querySelectorAll<HTMLInputElement>("input[name='mode']").forEach(input=>input.addEventListener("change",updateMode));updateMode();

  const mountTurnstile=()=>{const turnstile=(window as any).turnstile;if(!turnstile)return;widgetId=turnstile.render(root.querySelector("[data-turnstile-slot]")!,{sitekey:root.dataset.siteKey,action:"fanout",theme:"dark",callback:(token:string)=>turnstileToken=token,"expired-callback":()=>turnstileToken="","error-callback":()=>turnstileToken=""})};
  if(root.dataset.enabled==="true"&&root.dataset.siteKey){if((window as any).turnstile)mountTurnstile();else{const existing=document.querySelector<HTMLScriptElement>('script[src*="challenges.cloudflare.com/turnstile"]');if(existing)existing.addEventListener("load",mountTurnstile,{once:true});else{const script=document.createElement("script");script.src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";script.async=true;script.defer=true;script.addEventListener("load",mountTurnstile,{once:true});document.head.append(script)}}}
  const setLoadingStep=(active:number)=>loadingSteps.forEach((step,index)=>{step.classList.toggle("is-done",index<active);step.classList.toggle("is-active",index===active)}),startLoading=()=>{let elapsed=0;loadingSeconds.textContent="0";setLoadingStep(1);loadingDialog.showModal();loadingTimer=window.setInterval(()=>{elapsed++;loadingSeconds.textContent=String(elapsed)},1000)},stopLoading=()=>{if(loadingTimer!==undefined)window.clearInterval(loadingTimer);loadingTimer=undefined;if(loadingDialog.open)loadingDialog.close()};loadingDialog.addEventListener("cancel",event=>event.preventDefault());

  form.addEventListener("submit",async(event)=>{event.preventDefault();status.textContent="";const selectedMode=mode();if(!modeEnabled(selectedMode)){availability.hidden=false;return}if(!turnstileToken){status.textContent=locale==="de"?"Bitte warte kurz auf die Sicherheitsprüfung.":"Please wait for the security check.";return}submit.disabled=true;submit.firstChild!.textContent=root.dataset.loadingLabel??"Loading …";startLoading();try{const data=new FormData(form),common={keyword:keyword.value,country:String(data.get("country")??""),language:String(data.get("language")??"en"),turnstileToken},request=selectedMode==="native"?{...common,provider:String(data.get("provider")??"")}:{...common,model:String(data.get("model")??"")};const response=await fetch(selectedMode==="native"?"/api/native-fanout":"/api/fanout-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)}),payload=await response.json();if(!response.ok){if(payload?.error?.quota)renderQuota(payload.error.quota,true);throw new Error(publicError(payload?.error))}setLoadingStep(3);lastResult=payload.data;if(lastResult?.quota)renderQuota(lastResult.quota);render(lastResult!);await new Promise(resolve=>window.setTimeout(resolve,180));stopLoading();dialog.showModal()}catch(error){stopLoading();status.textContent=error instanceof Error?error.message:"The fanout could not be generated."}finally{submit.disabled=!modeEnabled(mode());submit.firstChild!.textContent=root.dataset.submitLabel??"Show search queries";turnstileToken="";const turnstile=(window as any).turnstile;if(turnstile&&widgetId!==undefined)turnstile.reset(widgetId)}});

  root.querySelector("[data-dialog-close]")?.addEventListener("click",()=>dialog.close());root.querySelector("[data-new-keyword]")?.addEventListener("click",()=>{dialog.close();keyword.focus();keyword.select()});dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});root.querySelector("[data-comparison-close]")?.addEventListener("click",()=>comparisonDialog.close());comparisonDialog.addEventListener("click",event=>{if(event.target===comparisonDialog)comparisonDialog.close()});
  root.querySelector("[data-copy-results]")?.addEventListener("click",async event=>{if(!lastResult)return;const button=event.currentTarget as HTMLButtonElement;await navigator.clipboard.writeText(lastResult.queries.map((item,index)=>`${index+1}. ${queryText(item)}`).join("\n"));const original=button.textContent;button.textContent=root.dataset.copiedLabel??"Copied";setTimeout(()=>button.textContent=original,1600)});
  saveResult.addEventListener("click",async()=>{if(!lastResult)return;try{await saveRun(lastResult);saveResult.textContent=ui.saved;saveResult.disabled=true;if(lastResult.providerId==="gemini")root.querySelector<HTMLElement>("[data-result-notice]")!.textContent=`${lastResult.notice} ${ui.geminiSaved}`;await refreshHistory()}catch{status.textContent=ui.saveError}});
  root.querySelector("[data-download-json]")?.addEventListener("click",()=>lastResult&&download(`${fileStem(lastResult)}.json`,JSON.stringify(lastResult,null,2),"application/json"));root.querySelector("[data-download-csv]")?.addEventListener("click",()=>lastResult&&download(`${fileStem(lastResult)}.csv`,toCsv(lastResult),"text/csv;charset=utf-8"));clearHistory.addEventListener("click",async()=>{if(clearHistory.dataset.confirming!=="true"){clearHistory.dataset.confirming="true";clearHistory.textContent=ui.clearConfirm;if(clearResetTimer!==undefined)window.clearTimeout(clearResetTimer);clearResetTimer=window.setTimeout(resetClearButton,5000);return}await clearSavedRuns();selectedIds.clear();resetClearButton();await refreshHistory()});compareRuns.addEventListener("click",showComparison);exportRunsJson.addEventListener("click",()=>downloadSelected("json"));exportRunsCsv.addEventListener("click",()=>downloadSelected("csv"));refreshHistory();

  async function refreshHistory(){try{historyEntries=await loadSavedRuns() as HistoryEntry[];renderHistory(historyEntries)}catch{historyList.replaceChildren();historyEmpty.textContent=ui.historyError;historyEmpty.hidden=false;clearHistory.hidden=true;historyTools.hidden=true}}
  function resetClearButton(){if(clearResetTimer!==undefined)window.clearTimeout(clearResetTimer);clearResetTimer=undefined;delete clearHistory.dataset.confirming;clearHistory.textContent=ui.clear}
  function renderHistory(entries:HistoryEntry[]){historyList.replaceChildren();historyEmpty.textContent=ui.empty;historyEmpty.hidden=entries.length>0;clearHistory.hidden=entries.length===0;historyTools.hidden=entries.length===0;resetClearButton();const validIds=new Set(entries.map(entry=>entry.id));for(const id of selectedIds)if(!validIds.has(id))selectedIds.delete(id);for(const entry of entries){const li=document.createElement("li"),selectLabel=document.createElement("label"),checkbox=document.createElement("input"),check=document.createElement("span"),details=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("div"),provider=document.createElement("span"),queries=document.createElement("span"),date=document.createElement("span"),actions=document.createElement("div"),open=document.createElement("button"),remove=document.createElement("button");li.className="saved-run";selectLabel.className="saved-run-select";check.className="saved-run-check";check.setAttribute("aria-hidden","true");details.className="saved-run-copy";meta.className="saved-run-meta";actions.className="saved-run-actions";open.className="saved-run-open";remove.className="saved-run-remove";checkbox.type="checkbox";checkbox.checked=selectedIds.has(entry.id);checkbox.setAttribute("aria-label",`${ui.select}: ${entry.result.keyword}`);checkbox.addEventListener("change",()=>{checkbox.checked?selectedIds.add(entry.id):selectedIds.delete(entry.id);updateSelection()});title.textContent=entry.result.keyword;provider.textContent=modelLabel(entry.result.modelId);queries.textContent=locale==="de"?`${entry.result.queries.length} Queries`:`${entry.result.queries.length} queries`;date.textContent=new Date(entry.savedAt).toLocaleDateString(locale,{dateStyle:"medium"});open.type="button";open.textContent=ui.open;remove.type="button";remove.textContent=ui.remove;open.addEventListener("click",()=>{lastResult=entry.result;render(lastResult,true);dialog.showModal()});remove.addEventListener("click",async()=>{selectedIds.delete(entry.id);await deleteSavedRun(entry.id);await refreshHistory()});selectLabel.append(checkbox,check);meta.append(provider,queries,date);details.append(title,meta);actions.append(open,remove);li.append(selectLabel,details,actions);historyList.append(li)}updateSelection()}
  function updateSelection(){selectedCount.textContent=String(selectedIds.size);const enough=selectedIds.size>=2;compareRuns.disabled=!enough;exportRunsJson.disabled=!enough;exportRunsCsv.disabled=!enough}
  function selectedEntries(){return historyEntries.filter(entry=>selectedIds.has(entry.id))}
  function downloadSelected(format:"json"|"csv"){const comparison=compareFanoutRuns(selectedEntries());download(`ai-fanout-comparison-${new Date().toISOString().slice(0,10)}.${format}`,format==="json"?JSON.stringify(comparison,null,2):comparisonCsv(comparison),format==="json"?"application/json":"text/csv;charset=utf-8")}
  function showComparison(){const comparison=compareFanoutRuns(selectedEntries()),summary=root.querySelector<HTMLElement>("[data-comparison-summary]")!,runs=root.querySelector<HTMLElement>("[data-comparison-runs]")!;summary.replaceChildren();for(const text of [locale==="de"?`${comparison.runCount} Läufe`:`${comparison.runCount} runs`,locale==="de"?`${comparison.sharedQueries.length} identische Queries`:`${comparison.sharedQueries.length} exact query matches`,locale==="de"?`${comparison.sharedSourceDomains.length} gemeinsame Quellendomains`:`${comparison.sharedSourceDomains.length} shared source domains`]){const span=document.createElement("span");span.textContent=text;summary.append(span)}runs.replaceChildren();for(const run of comparison.runs){const article=document.createElement("article"),label=document.createElement("span"),title=document.createElement("h3"),meta=document.createElement("p"),list=document.createElement("ol");label.textContent=`${run.providerId.toUpperCase()} · ${new Date(run.savedAt).toLocaleString(locale)}`;title.textContent=run.keyword;meta.textContent=`${modelLabel(run.modelId)} · ${run.analysis.comparisonQuestionCount} ${locale==="de"?"Vergleich":"comparison"} · ${run.analysis.priceQuestionCount} ${locale==="de"?"Preis":"price"}`;for(const item of run.queries){const li=document.createElement("li");li.textContent=queryText(item);list.append(li)}article.append(label,title,meta,list);runs.append(article)}comparisonDialog.showModal()}

  function render(result:FanoutResult,saved=false){const native=result.evidenceStatus==="provider_exposed_native_search",analysis=analyzeFanout(result);root.querySelector<HTMLElement>("[data-result-keyword]")!.textContent=result.keyword;root.querySelector<HTMLElement>("[data-result-count]")!.textContent=String(result.queries.length);root.querySelector<HTMLElement>("[data-result-model]")!.textContent=native?`${modelLabel(result.modelId)} via ${result.providerId==="gemini"?"Gemini API":"OpenAI API"}`:`${modelLabel(result.modelId)} via OpenRouter`;root.querySelector<HTMLElement>("[data-result-evidence]")!.textContent=native?(locale==="de"?"Vom Anbieter offengelegte API-Suchaktionen":"Provider-exposed API search actions"):(locale==="de"?"Modellierte Suchideen ohne Websuche":"Modelled search ideas without web search");const market=result.country?(countryNames[result.country]??result.country):(locale==="de"?"Alle Länder":"All countries");root.querySelector<HTMLElement>("[data-result-locale]")!.textContent=`${market} · ${result.language==="de"?"Deutsch":"English"}`;root.querySelector<HTMLElement>("[data-result-date]")!.textContent=new Date(result.generatedAt).toLocaleString(result.language);const partial=result.providerResponseStatus==="incomplete"?(locale==="de"?" Die Suchaktion war vollständig sichtbar; nur die ungenutzte Abschlussantwort erreichte das Tokenlimit.":" The search action was visible; only the unused final answer reached its token cap."):"";root.querySelector<HTMLElement>("[data-result-notice]")!.textContent=`${result.notice}${partial}${result.storageNotice?` ${result.storageNotice}`:""}`;saveResult.textContent=saved?ui.saved:ui.save;saveResult.disabled=saved;renderAnalysis(result,analysis);renderQueries(result);renderUsage(result.usage)}
  function renderAnalysis(result:FanoutResult,analysis:any){const actionCount=result.searchActionCount??0,queryCount=analysis.observedQueryCount;root.querySelector<HTMLElement>("[data-summary-queries]")!.textContent=String(queryCount);root.querySelector<HTMLElement>("[data-summary-domains]")!.textContent=String(analysis.distinctSourceDomainCount);root.querySelector<HTMLElement>("[data-summary-actions]")!.textContent=String(actionCount);root.querySelector<HTMLElement>("[data-summary-comparisons]")!.textContent=String(analysis.comparisonQuestionCount);root.querySelector<HTMLElement>("[data-summary-prices]")!.textContent=String(analysis.priceQuestionCount);root.querySelector<HTMLElement>("[data-summary-relation]")!.textContent=locale==="de"?`${actionCount} Anbieter-Suchaktion${actionCount===1?"":"en"} enthielt${actionCount===1?"":"en"} ${queryCount} sichtbare Query-Strings. Eine Suchaktion kann mehrere Queries bündeln.`:`${actionCount} provider search action${actionCount===1?"":"s"} contained ${queryCount} visible query string${queryCount===1?"":"s"}. One search action can bundle several queries.`;const themes=root.querySelector<HTMLUListElement>("[data-summary-themes]")!;themes.replaceChildren();for(const theme of analysis.recurringThemes){const li=document.createElement("li");li.textContent=`${theme.term} ×${theme.count}`;themes.append(li)}if(!analysis.recurringThemes.length){const li=document.createElement("li");li.textContent=ui.themesEmpty;themes.append(li)}}
  function renderQueries(result:FanoutResult){const exactByQuery=new Map<string,{sources:Source[];scope:string}>(),mappedUrls=new Set<string>();for(const action of result.searchActions??[]){if(action.sources?.length&&action.queries?.length===1){exactByQuery.set(action.queries[0].normalize("NFKC").toLowerCase(),{sources:action.sources,scope:action.sourceScope});for(const source of action.sources)mappedUrls.add(source.url)}}const queries=root.querySelector<HTMLOListElement>("[data-result-queries]")!;queries.replaceChildren();if(result.queries.length===0){const li=document.createElement("li"),title=document.createElement("strong");title.textContent=locale==="de"?"In diesem Lauf hat die API keine Query-Strings offengelegt.":"The API exposed no query strings in this run.";li.append(title);queries.append(li)}result.queries.forEach((item,index)=>{const text=queryText(item),li=document.createElement("li"),number=document.createElement("span"),title=document.createElement("strong");number.textContent=String(index+1).padStart(2,"0");title.textContent=text;li.append(number,title);if(typeof item!=="string"){const meta=document.createElement("div"),intent=document.createElement("span"),reason=document.createElement("p");intent.textContent=`${locale==="de"?"Intent":"Intent"}: ${intentLabel(item.intent)}`;reason.textContent=`${locale==="de"?"Warum":"Why"}: ${item.reason}`;meta.append(intent,reason);li.append(meta)}const mapping=exactByQuery.get(text.normalize("NFKC").toLowerCase());if(mapping){const box=document.createElement("div"),label=document.createElement("p"),list=document.createElement("ul");box.className="query-sources";label.textContent=mapping.scope==="exact_query"?ui.exactSources:ui.actionSources;for(const source of mapping.sources)appendSource(list,source);box.append(label,list);li.append(box)}queries.append(li)});const globalSources=(result.sources??[]).filter(source=>!mappedUrls.has(source.url)),sourceSection=root.querySelector<HTMLElement>("[data-result-sources-section]")!,sources=root.querySelector<HTMLUListElement>("[data-result-sources]")!;sources.replaceChildren();sourceSection.hidden=!globalSources.length;const multiAction=(result.searchActions??[]).some(action=>action.queries.length>1&&action.sources.length);root.querySelector<HTMLElement>("[data-result-sources-title]")!.textContent=multiAction?(locale==="de"?"Quellen zur gemeinsamen Suchaktion":"Sources linked to the shared search action"):ui.globalSources;root.querySelector<HTMLElement>("[data-result-sources-note]")!.textContent=multiAction?(locale==="de"?"Der Provider übermittelte diese Quellen zusammen mit mehreren Queries in einer Suchaktion. Eine feinere Zuordnung wäre erfunden.":"The provider transmitted these sources with several queries in one search action. A more precise link would be invented."):ui.globalSourceNote;for(const source of globalSources)appendSource(sources,source)}
  function renderUsage(usage?:Usage){const section=root.querySelector<HTMLElement>("[data-result-cost]")!;section.hidden=!usage;if(!usage)return;root.querySelector<HTMLElement>("[data-usage-input]")!.textContent=usage.inputTokens.toLocaleString(locale);root.querySelector<HTMLElement>("[data-usage-output]")!.textContent=usage.outputTokens.toLocaleString(locale);root.querySelector<HTMLElement>("[data-usage-searches]")!.textContent=String(usage.searchActionCount);const min=money(usage.estimatedCostUsd),max=usage.estimatedCostUsdMaximum;root.querySelector<HTMLElement>("[data-usage-cost]")!.textContent=max!==undefined&&max>usage.estimatedCostUsd?`${min}–${money(max)}`:min;root.querySelector<HTMLElement>("[data-usage-basis]")!.textContent=`${usage.pricingBasis} ${locale==="de"?"Preisstand":"Checked"}: ${usage.pricingCheckedAt}.`}
  function appendSource(list:HTMLUListElement,source:Source){let parsed:URL;try{parsed=new URL(source.url)}catch{return}if(!["http:","https:"].includes(parsed.protocol))return;const li=document.createElement("li"),link=document.createElement("a");link.href=parsed.href;link.target="_blank";link.rel="noopener noreferrer";link.textContent=source.title||sourceDomain(source);li.append(link);list.append(li)}
  function renderQuota(quota:Quota,limited=false){if(!quota||!Number.isFinite(quota.limit)||!Number.isFinite(quota.remaining))return;const reset=new Date(quota.resetAt),validReset=!Number.isNaN(reset.getTime());quotaStatus.dataset.state=limited||quota.remaining===0?"limited":"available";quotaStatus.textContent=locale==="de"?`${quota.remaining} von ${quota.limit} kostenlosen Läufen übrig${validReset?` · Reset ${reset.toLocaleString("de-DE",{dateStyle:"medium",timeStyle:"short"})}`:""}.`:`${quota.remaining} of ${quota.limit} free runs remaining${validReset?` · resets ${reset.toLocaleString("en",{dateStyle:"medium",timeStyle:"short"})}`:""}.`}
  function publicError(error:any){if(error?.code==="RATE_LIMIT"&&error?.quota){const reset=new Date(error.quota.resetAt),when=Number.isNaN(reset.getTime())?"":reset.toLocaleString(locale==="de"?"de-DE":"en",{dateStyle:"medium",timeStyle:"short"});return locale==="de"?`${error.quota.limit} von ${error.quota.limit} kostenlosen Läufen verwendet.${when?` Wieder verfügbar am ${when}.`:""}`:`${error.quota.limit} of ${error.quota.limit} free runs used.${when?` Available again ${when}.`:""}`}if(error?.code==="GLOBAL_LIMIT")return ui.globalLimit;if(error?.code==="BUDGET_LIMIT")return ui.budgetLimit;return error?.message||"The fanout could not be generated."}
  function fileStem(result:FanoutResult){return `ai-fanout-${result.keyword.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"result"}`}
  function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement("a");link.href=url;link.download=name;link.hidden=true;document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function toCsv(result:FanoutResult){const rows=[["type","index","query","intent","reason","source_scope","url","title","input_tokens","output_tokens","estimated_cost_usd"],...result.queries.map((item,index)=>["query",String(index+1),queryText(item),typeof item==="string"?"":item.intent,typeof item==="string"?"":item.reason,"","","",String(result.usage?.inputTokens??""),String(result.usage?.outputTokens??""),String(result.usage?.estimatedCostUsd??"")]),...(result.searchActions??[]).flatMap(action=>action.sources.map(source=>["query_source","",action.queries.join(" | "),"","",action.sourceScope,source.url,source.title,"","",""])),...(result.sources??[]).map(source=>["run_source","","","","","run_level",source.url,source.title,"","",""])];return rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")}
  function money(value:number){return new Intl.NumberFormat(locale,{style:"currency",currency:"USD",minimumFractionDigits:value<.01?4:2,maximumFractionDigits:value<.01?4:2}).format(value)}
  function modelLabel(id:string){return id.includes("gpt-5.6-luna")?"GPT-5.6 Luna":id.includes("gemini-3.7-flash")?"Gemini 3.7 Flash":id}
  function intentLabel(intent:string){const labels:Record<string,Record<string,string>>={de:{informational:"Information",comparison:"Vergleich",commercial:"Kommerziell",transactional:"Transaktion",local:"Lokal",troubleshooting:"Problemlösung"},en:{informational:"Informational",comparison:"Comparison",commercial:"Commercial",transactional:"Transactional",local:"Local",troubleshooting:"Troubleshooting"}};return labels[locale]?.[intent]??intent}
}
