import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
const root=resolve(new URL("..",import.meta.url).pathname.replace(/^\/(.:)/,"$1")),dist=join(root,"dist"),failures=[];
const check=(value,message)=>{if(!value)failures.push(message)};
const read=route=>readFile(route==="/"?join(dist,"index.html"):join(dist,route.slice(1),"index.html"),"utf8");
const home=await read("/"),de=await read("/de"),method=await read("/methodology"),privacy=await read("/datenschutz");
check(home.includes("Observed search queries")&&home.includes("Websites used"),"English result contract");check(de.includes("Beobachtete Suchanfragen")&&de.includes("Verwendete Websites"),"German result contract");check(home.includes("real OpenRouter response test")&&home.includes("disabled"),"fail-closed status");
for(const value of ["OpenAI via OpenRouter","eight tool calls","12 seconds","five attempts","€25","€30","€0.15"])check(method.includes(value),`method missing ${value}`);
for(const value of ["OpenRouter","OpenAI","store: false","kein eigenes Geräte-Cookie"])check(privacy.includes(value),`privacy missing ${value}`);
const source=await readFile(join(root,"src/server/fanout/provider.mjs"),"utf8"),api=await readFile(join(root,"api/fanout-plan.ts"),"utf8");check(source.includes("https://openrouter.ai/api/v1/responses")&&source.includes("openrouter:web_search")&&source.includes("max_tool_calls: MAX_SEARCH_CALLS"),"provider contract");check(api.includes("FANOUT_PUBLIC_ENABLED")&&api.includes("OPENROUTER_API_KEY")&&!api.includes("PUBLIC_OPENROUTER"),"server secret gate");
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log("Tool QA passed: bilingual UI, observed-query boundary, privacy, cost limits and server-only secret gate.");
