import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_MODEL_ID, FANOUT_QUERY_COUNT, MODEL_IDS, REQUEST_RESERVE_MICRO_EUR, TOOL_VERSION, ToolError, validateKeyword } from "../src/server/fanout/contracts.mjs";
import { OpenRouterFanoutProvider } from "../src/server/fanout/provider.mjs";
import { MemoryQuotaLedger } from "../src/server/fanout/quota.mjs";
import { createFanoutService, verifyTurnstile } from "../src/server/fanout/service.mjs";

const queries=Array.from({length:FANOUT_QUERY_COUNT},(_,index)=>({query:`SEO research angle ${index+1}`,intent:index%2?"comparison":"informational",reason:`Distinct research reason ${index+1}`}));
const okProvider={generate:async({model})=>({result:{queries},inputTokens:100,outputTokens:300,actualCostMicroEur:1_000,latencyMs:20,model,provider:"openrouter"})};
const create=({ledger=new MemoryQuotaLedger(),provider=okProvider}={})=>{let captchaCalls=0;const service=createFanoutService({ledger,provider,bucketSalt:"test-salt",now:()=>new Date("2026-08-26T12:00:00Z"),captchaVerifier:async token=>{captchaCalls++;if(token!=="valid")throw new ToolError("CAPTCHA_FAILED",403)}});return{ledger,service,get captchaCalls(){return captchaCalls}}};
const body={keyword:"SEO tools",model:DEFAULT_MODEL_ID,language:"en",country:"DE",turnstileToken:"valid"};

test("allowlists exactly the three approved models",()=>{assert.deepEqual(MODEL_IDS,["openai/gpt-5.6-luna","deepseek/deepseek-v4-flash-0731","google/gemini-3.7-flash"])});
test("validates Unicode, byte, URL, file and multiline limits",()=>{assert.equal(validateKeyword("  SEO tools  "),"SEO tools");assert.throws(()=>validateKeyword("x"),/KEYWORD_TOO_SHORT/);assert.throws(()=>validateKeyword("🙂".repeat(61)),/KEYWORD_TOO_LONG/);assert.throws(()=>validateKeyword("https://example.com"),/URL_NOT_ALLOWED/);assert.throws(()=>validateKeyword("upload report.pdf"),/FILES_NOT_ALLOWED/);assert.throws(()=>validateKeyword("seo\ntools"),/KEYWORD_MULTILINE/)});
test("request is strict and rejects a model outside the allowlist before CAPTCHA",async()=>{const ctx=create();await assert.rejects(()=>ctx.service({body:{...body,model:"openai/other"},remoteIp:"1.2.3.4"}),/INVALID_REQUEST/);await assert.rejects(()=>ctx.service({body:{...body,extra:"no"},remoteIp:"1.2.3.4"}),/INVALID_REQUEST/);assert.equal(ctx.captchaCalls,0)});
test("failed CAPTCHA does not reserve budget",async()=>{const ctx=create();await assert.rejects(()=>ctx.service({body:{...body,turnstileToken:"bad"},remoteIp:"1.2.3.4"}),/CAPTCHA_FAILED/);assert.equal(ctx.ledger.records.size,0)});
test("Turnstile requires success, expected action and approved hostname",async()=>{const expectedHostnames=new Set(["ai-fanout.com"]);const verify=result=>verifyTurnstile({token:"valid",secret:"secret",remoteIp:"1.2.3.4",expectedAction:"fanout",expectedHostnames,fetchImpl:async()=>({ok:true,json:async()=>result})});await assert.doesNotReject(()=>verify({success:true,action:"fanout",hostname:"ai-fanout.com"}));await assert.rejects(()=>verify({success:true,action:"other",hostname:"ai-fanout.com"}),/CAPTCHA_FAILED/);await assert.rejects(()=>verify({success:true,action:"fanout",hostname:"attacker.example"}),/CAPTCHA_FAILED/)});
test("five runs per hashed IP bucket and sixth is blocked",async()=>{const ctx=create();for(let i=0;i<5;i++)await ctx.service({body:{...body,keyword:`SEO tools ${i}`},remoteIp:"1.2.3.4"});await assert.rejects(()=>ctx.service({body:{...body,keyword:"SEO tools six"},remoteIp:"1.2.3.4"}),/RATE_LIMIT/)});
test("global daily limit blocks run 41",async()=>{const ctx=create();for(let i=0;i<40;i++)await ctx.service({body:{...body,keyword:`SEO topic ${i}`},remoteIp:`10.0.0.${i}`});await assert.rejects(()=>ctx.service({body:{...body,keyword:"last topic"},remoteIp:"10.0.1.1"}),/GLOBAL_LIMIT/)});
test("parallel reservations cannot cross hard monthly budget",async()=>{const ledger=new MemoryQuotaLedger({spent:24_980_000});ledger.reserved=4_700_000;const calls=[1,2,3].map(i=>ledger.reserve({bucketHash:`b${i}`,reservationId:`r${i}`,questionHash:`q${i}`,model:DEFAULT_MODEL_ID,plannerVersion:TOOL_VERSION}));const settled=await Promise.allSettled(calls);assert.equal(settled.filter(item=>item.status==="fulfilled").length,2);assert.equal(settled.filter(item=>item.status==="rejected"&&item.reason.code==="BUDGET_LIMIT").length,1);assert.equal(ledger.reserved,4_700_000+2*REQUEST_RESERVE_MICRO_EUR)});
test("provider failure settles reservation and stores no raw input",async()=>{const ctx=create({provider:{generate:async()=>{throw new ToolError("PROVIDER_UNAVAILABLE",502)}}});await assert.rejects(()=>ctx.service({body,remoteIp:"1.2.3.4"}),/PROVIDER_UNAVAILABLE/);const record=[...ctx.ledger.records.values()][0];assert.equal(record.status,"failed");assert.equal(ctx.ledger.reserved,0);assert.equal(JSON.stringify(record).includes(body.keyword),false)});
test("timeout is surfaced with one provider call",async()=>{let calls=0;const ctx=create({provider:{generate:async()=>{calls++;throw new ToolError("PROVIDER_TIMEOUT",504)}}});await assert.rejects(()=>ctx.service({body,remoteIp:"1.2.3.4"}),/PROVIDER_TIMEOUT/);assert.equal(calls,1);assert.equal([...ctx.ledger.records.values()][0].status,"timeout")});
test("OpenRouter request is one bounded structured-output call with no client secret",async()=>{
  let calls=0,request;
  const provider=new OpenRouterFanoutProvider({apiKey:"server-secret",fetchImpl:async(url,options)=>{
    calls++;request={url,options,body:JSON.parse(options.body)};
    return {ok:true,json:async()=>({model:DEFAULT_MODEL_ID,choices:[{message:{content:JSON.stringify({queries})}}],usage:{prompt_tokens:10,completion_tokens:250,cost:0.001}})};
  }});
  const generated=await provider.generate({keyword:"SEO tools",model:DEFAULT_MODEL_ID,language:"en",country:"DE"});
  assert.equal(calls,1);assert.equal(request.url,"https://openrouter.ai/api/v1/chat/completions");assert.equal(request.body.model,DEFAULT_MODEL_ID);assert.equal(request.body.max_tokens,800);assert.equal(request.body.response_format.type,"json_schema");assert.equal(request.body.response_format.json_schema.strict,true);assert.equal(JSON.stringify(request.body).includes("hidden provider searches"),true);assert.equal(JSON.stringify(request.body).includes("server-secret"),false);assert.equal(request.options.headers.Authorization,"Bearer server-secret");assert.equal(generated.result.queries.length,10);
});
test("provider rejects malformed or short output",async()=>{const provider=new OpenRouterFanoutProvider({apiKey:"x",fetchImpl:async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({queries:queries.slice(0,1)})}}]})})});await assert.rejects(()=>provider.generate({keyword:"SEO tools",model:DEFAULT_MODEL_ID,language:"en",country:""}),/PROVIDER_INVALID_OUTPUT/)});
test("successful output is dated, model-specific and truthfully labelled",async()=>{const data=await create().service({body,remoteIp:"1.2.3.4"});assert.equal(data.keyword,"SEO tools");assert.equal(data.queries.length,10);assert.equal(data.modelId,DEFAULT_MODEL_ID);assert.equal(data.evidenceStatus,"modelled_fanout");assert.equal(data.generatedAt,"2026-08-26T12:00:00.000Z");assert.match(data.notice,/not hidden provider queries/i);assert.equal(data.toolVersion,TOOL_VERSION)});
