import test from "node:test";import assert from "node:assert/strict";import {PlannerError,MODEL_ID,PLANNER_VERSION,validateQuestion} from "../src/server/fanout/contracts.mjs";import {MemoryQuotaLedger} from "../src/server/fanout/quota.mjs";import {OpenAIPlannerProvider} from "../src/server/fanout/provider.mjs";import {createPlannerService} from "../src/server/fanout/service.mjs";
const validPlan={summary:"A transparent set of plausible research branches for this question.",branches:Array.from({length:4},(_,i)=>({query:`Useful branch question number ${i+1}`,intent:"learn",rationale:"This branch clarifies a distinct part of the user's question.",sourceType:"primary documentation",assumption:"The user needs a practical overview."}))};const okProvider={generate:async()=>({plan:validPlan,inputTokens:100,outputTokens:500,actualCostMicroEur:645,latencyMs:20,model:MODEL_ID})};const create=(options={})=>{const ledger=options.ledger??new MemoryQuotaLedger();let captchaCalls=0;const service=createPlannerService({ledger,provider:options.provider??okProvider,bucketSalt:"test-salt",captchaVerifier:async(token)=>{captchaCalls++;if(token!=="valid")throw new PlannerError("CAPTCHA_FAILED",403)}});return{ledger,service,get captchaCalls(){return captchaCalls}}};
test("question caps count Unicode and UTF-8 bytes",()=>{assert.equal([...validateQuestion("a".repeat(120))].length,120);assert.throws(()=>validateQuestion("a".repeat(121)),/QUESTION_TOO_LONG/);assert.throws(()=>validateQuestion("😀".repeat(70)),/QUESTION_TOO_LONG/);assert.throws(()=>validateQuestion("See https:\/\/example.com"),/URL_NOT_ALLOWED/);assert.throws(()=>validateQuestion("Please attach report.pdf"),/FILES_NOT_ALLOWED/)});
test("strict request rejects extra context before CAPTCHA",async()=>{const ctx=create();await assert.rejects(()=>ctx.service({body:{question:"How should this work?",turnstileToken:"valid",context:"secret"},remoteIp:"1.2.3.4"}),/INVALID_REQUEST/);assert.equal(ctx.captchaCalls,0)});
test("CAPTCHA failure creates no reservation or provider call",async()=>{let calls=0;const ctx=create({provider:{generate:async()=>{calls++;return okProvider.generate()}}});await assert.rejects(()=>ctx.service({body:{question:"How should this work?",turnstileToken:"bad"},remoteIp:"1.2.3.4"}),/CAPTCHA_FAILED/);assert.equal(calls,0);assert.equal(ctx.ledger.records.size,0)});
test("anonymous bucket permits only two attempts per 24-hour window",async()=>{const ctx=create();for(let i=0;i<2;i++)await ctx.service({body:{question:`How should this work ${i}?`,turnstileToken:"valid"},remoteIp:"1.2.3.4",deviceId:"device"});await assert.rejects(()=>ctx.service({body:{question:"How should attempt three work?",turnstileToken:"valid"},remoteIp:"1.2.3.4",deviceId:"device"}),/RATE_LIMIT/)});
test("global daily cap is enforced",async()=>{const ledger=new MemoryQuotaLedger();ledger.daily=40;const ctx=create({ledger});await assert.rejects(()=>ctx.service({body:{question:"How should this work?",turnstileToken:"valid"},remoteIp:"1.2.3.4",deviceId:"device"}),/GLOBAL_LIMIT/)});
test("parallel reservations cannot pass hard monthly budget",async()=>{const ledger=new MemoryQuotaLedger({spent:24_980_000});ledger.reserved=5_000_000;const results=await Promise.allSettled([ledger.reserve({bucketHash:"a",reservationId:"1",questionHash:"q1",model:MODEL_ID,plannerVersion:PLANNER_VERSION}),ledger.reserve({bucketHash:"b",reservationId:"2",questionHash:"q2",model:MODEL_ID,plannerVersion:PLANNER_VERSION})]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected"&&r.reason.code==="BUDGET_LIMIT").length,1);assert.equal(ledger.reserved,5_020_000)});
test("provider error releases reservation but consumes attempt",async()=>{const ctx=create({provider:{generate:async()=>{throw new PlannerError("PROVIDER_UNAVAILABLE",502)}}});await assert.rejects(()=>ctx.service({body:{question:"How should this work?",turnstileToken:"valid"},remoteIp:"1.2.3.4",deviceId:"device"}),/PROVIDER_UNAVAILABLE/);assert.equal(ctx.ledger.reserved,0);assert.equal([...ctx.ledger.records.values()][0].status,"failed")});
test("provider timeout is mapped without a retry",async()=>{let calls=0;const provider=new OpenAIPlannerProvider({apiKey:"secret",fetchImpl:async()=>{calls++;throw new DOMException("timed out","TimeoutError")}});await assert.rejects(()=>provider.generate("How should this work?"),error=>error.code==="PROVIDER_TIMEOUT");assert.equal(calls,1)});
test("provider makes exactly one call and validates strict output",async()=>{let calls=0;const provider=new OpenAIPlannerProvider({apiKey:"secret",fetchImpl:async(_url,init)=>{calls++;const body=JSON.parse(init.body);assert.equal(body.model,MODEL_ID);assert.equal(body.max_output_tokens,700);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);return new Response(JSON.stringify({model:MODEL_ID,output:[{content:[{type:"output_text",text:JSON.stringify(validPlan)}]}],usage:{input_tokens:100,output_tokens:500}}),{status:200})}});const result=await provider.generate("How should this work?");assert.equal(calls,1);assert.equal(result.plan.branches.length,4);assert.ok(result.actualCostMicroEur<20_000)});
test("operational ledger never stores raw question or output",async()=>{const ctx=create();const question="Unique raw prompt that must not persist";const result=await ctx.service({body:{question,turnstileToken:"valid"},remoteIp:"1.2.3.4",deviceId:"device"});const serialized=JSON.stringify([...ctx.ledger.records.values()]);assert.ok(!serialized.includes(question));assert.ok(!serialized.includes(result.data.summary));assert.ok(serialized.includes("questionHash"))});



