import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
const root=resolve(new URL("..",import.meta.url).pathname.replace(/^\/(.:)/,"$1")),dist=join(root,"dist"),failures=[];
const check=(value,message)=>{if(!value)failures.push(message)};
const read=route=>readFile(route==="/"?join(dist,"index.html"):join(dist,route.slice(1),"index.html"),"utf8");
const home=await read("/"),de=await read("/de"),method=await read("/methodology"),privacy=await read("/datenschutz");
check(home.includes("Build fanout")&&home.includes("GPT-5.6 Luna")&&home.includes("Gemini 3.7 Flash"),"English modelled-fanout UI");check(de.includes("Fanout erstellen")&&de.includes("Modellierter Fanout"),"German modelled-fanout UI");check(home.includes("data-result-dialog")&&home.includes("Copy all"),"result modal contract");
for(const value of ["GPT-5.6 Luna","DeepSeek V4 Flash","Gemini 3.7 Flash","20 seconds","Five attempts","€25","€30","€0.15"])check(method.includes(value),`method missing ${value}`);
for(const value of ["OpenRouter","OpenAI","DeepSeek","Google","kein eigenes Geräte-Cookie"])check(privacy.includes(value),`privacy missing ${value}`);
const source=await readFile(join(root,"src/server/fanout/provider.mjs"),"utf8"),api=await readFile(join(root,"api/fanout-plan.ts"),"utf8"),client=await readFile(join(root,"src/scripts/fanout-planner.ts"),"utf8");check(source.includes("https://openrouter.ai/api/v1/chat/completions")&&source.includes('type: "json_schema"')&&source.includes("max_tokens: MAX_OUTPUT_TOKENS"),"provider contract");check(api.includes("FANOUT_PUBLIC_ENABLED")&&api.includes("OPENROUTER_API_KEY")&&!api.includes("PUBLIC_OPENROUTER"),"server secret gate");check(client.includes('action:"fanout"'),"Turnstile action contract");check(/<script[^>]+src="\/_astro\//.test(home)&&!home.includes("for(const root of document.querySelectorAll"),"planner client must be an external same-origin asset under CSP");
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log("Tool QA passed: bilingual modelled-fanout UI, three-model allowlist, modal output, privacy, cost limits and server-only secret gate.");
