import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { preview } from "astro";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");const dist=join(root,"dist"),host="https://ai-fanout.com",failures=[];const check=(value,message)=>{if(!value)failures.push(message)};
const en=["what-is-ai-query-fanout","how-to-see-openai-search-queries","openai-web-search-queries","ai-citations","ai-query-fanout-for-seo","why-ai-fanout-results-change","country-language-ai-search","compare-ai-model-searches"];
const de=["was-ist-ai-query-fanout","openai-suchanfragen-sehen","openai-websuche","ki-zitate-und-quellen","query-fanout-fuer-seo","warum-fanout-ergebnisse-schwanken","land-und-sprache-ki-suche","ki-modelle-vergleichen"];
const indexable=["/","/de","/library","/de/lernen","/methodology","/de/methode",...en.map(s=>`/library/${s}`),...de.map(s=>`/de/lernen/${s}`),"/transparency","/impressum","/datenschutz"];
const noindex=["/tracker"];const retired=["/lab","/protocol-builder","/research","/research/methodology","/datasets","/protocols/example-2026-08-22"];
const pageFile=route=>route==="/"?join(dist,"index.html"):join(dist,route.replace(/^\//,""),"index.html");const htmls=new Map();const titles=new Map();const descriptions=new Map();
for(const route of [...indexable,...noindex]){try{const html=await readFile(pageFile(route),"utf8");htmls.set(route,html);const canonical=route==="/"?`${host}/`:`${host}${route}`;check(html.includes(`rel="canonical" href="${canonical}"`),`${route}: canonical`);check((html.match(/<h1\b/gi)??[]).length===1,`${route}: one h1`);check(html.includes("<main"),`${route}: main landmark`);check(noindex.includes(route)?html.includes('content="noindex, follow"'):!html.includes('<meta name="robots"'),`${route}: robots state`);const title=html.match(/<title>([^<]+)/)?.[1],description=html.match(/<meta name="description" content="([^"]+)/)?.[1];check(Boolean(title),`${route}: title`);check(Boolean(description),`${route}: description`);if(title){check(!titles.has(title),`${route}: duplicate title ${titles.get(title)}`);titles.set(title,route)}if(description){check(!descriptions.has(description),`${route}: duplicate description ${descriptions.get(description)}`);descriptions.set(description,route)}}catch{failures.push(`${route}: missing build file`)}}
for(const [a,b] of [["/","/de"],["/library","/de/lernen"],["/methodology","/de/methode"],...en.map((slug,i)=>[`/library/${slug}`,`/de/lernen/${de[i]}`])]){const ah=htmls.get(a)??"",bh=htmls.get(b)??"";check(ah.includes(`hreflang="de" href="${host}${b}"`),`${a}: de hreflang`);check(bh.includes(`hreflang="en" href="${a==="/"?host+"/":host+a}"`),`${b}: en hreflang`)}
const home=htmls.get("/")??"",homeDe=htmls.get("/de")??"";check(home.includes("Turn one keyword into ten follow-up searches."),"English homepage thesis");check(homeDe.includes("Mach aus einem Keyword zehn weiterführende Suchanfragen."),"German homepage thesis");for(const stale of ["Evidence Lab","Protocol Builder","Compare Answers","Want to compare AI answers?"])check(!home.includes(stale)&&!homeDe.includes(stale),`homepage stale concept: ${stale}`);check(home.includes('data-fanout-planner')&&home.includes('data-enabled="false"'),"tool must be present and fail closed in default build");
const privacy=htmls.get("/datenschutz")??"";for(const claim of ["OpenRouter","OpenAI","Cloudflare Turnstile","fünf Versuchen","kein eigenes Geräte-Cookie","keine Analytics-"])check(privacy.includes(claim),`privacy missing: ${claim}`);
const sitemap=await readFile(join(dist,"sitemap-0.xml"),"utf8"),robots=await readFile(join(dist,"robots.txt"),"utf8");for(const route of indexable){const loc=route==="/"?host:host+route.replace(/\/$/,"");check(sitemap.includes(`<loc>${loc}</loc>`),`sitemap missing ${route}`)}for(const route of noindex)check(!sitemap.includes(`<loc>${host}${route}</loc>`),`sitemap leaked ${route}`);check(robots.includes("Allow: /")&&robots.includes("Sitemap: https://ai-fanout.com/sitemap-index.xml")&&!robots.includes("Disallow: /"),"robots policy");
const routeExists=async path=>{if(path==="/"||[...indexable,...noindex,"/robots.txt","/sitemap-index.xml","/sitemap-0.xml"].includes(path))return true;try{if(path.startsWith("/_astro/")||path.startsWith("/examples/")){await access(join(dist,path.slice(1)));return true}await access(pageFile(path));return true}catch{return false}};for(const [route,html] of htmls)for(const match of html.matchAll(/href="([^"]+)"/g)){const href=match[1];if(!href.startsWith("/")||href.startsWith("//"))continue;const path=href.split(/[?#]/)[0];if(path)check(await routeExists(path),`${route}: broken link ${href}`)}
const all=[...htmls.values()].join("\n").toLowerCase();for(const claim of ["reveals chain of thought","accesses private retrieval traces","guaranteed rankings","independently verified by contextter"])check(!all.includes(claim),`forbidden claim: ${claim}`);
const server=await preview({root,logLevel:"silent",server:{host:"127.0.0.1",port:0}});try{for(const route of [...indexable,...noindex,"/robots.txt","/sitemap-index.xml"]){const requestPath=route!=="/"?route.replace(/\/$/,""):route;const response=await fetch(`http://${server.host}:${server.port}${requestPath}`,{redirect:"manual"});check(response.status===200,`${route}: HTTP ${response.status}`)}for(const route of [...retired,"/not-a-real-page"]){const response=await fetch(`http://${server.host}:${server.port}${route}`,{redirect:"manual"});check(response.status===404&&!response.headers.has("location"),`${route}: real 404`)} }finally{await server.stop()}
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log(`QA passed: ${indexable.length} indexable pages, ${noindex.length} noindex route and ${retired.length} retired 404 routes, bilingual hreflang, sitemap, robots and links.`);
