import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { preview } from "astro";
import { canonicalUrlForPath, noindexRoutes, retiredRoutes, sitemapRouteByPath, sitemapRoutes } from "../src/data/sitemap-registry.mjs";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");const dist=join(root,"dist"),host="https://ai-fanout.com",failures=[];const check=(value,message)=>{if(!value)failures.push(message)};
const indexable=sitemapRoutes.map(route=>route.path),noindex=[...noindexRoutes],retired=[...retiredRoutes];
const routeManifest=JSON.parse(await readFile(join(root,"manifests","route-actions.v1.json"),"utf8"));const vercelConfig=JSON.parse(await readFile(join(root,"vercel.json"),"utf8"));
const redirectKey=redirect=>`${redirect.source}|${redirect.destination}`;const manifestRedirects=new Set(routeManifest.contentConsolidationRedirects.map(redirectKey));const vercelRedirects=new Set(vercelConfig.redirects.filter(redirect=>redirect.permanent).map(redirectKey));
for(const redirect of routeManifest.contentConsolidationRedirects){check(redirect.status===308,`${redirect.source}: route manifest redirect must be 308`);check(vercelRedirects.has(redirectKey(redirect)),`${redirect.source}: missing permanent Vercel redirect`);check(!indexable.includes(redirect.source),`${redirect.source}: redirect source leaked into sitemap registry`);check(indexable.includes(redirect.destination),`${redirect.source}: redirect target is not indexable`)}
for(const redirect of vercelConfig.redirects.filter(redirect=>redirect.source.startsWith("/library/")||redirect.source.startsWith("/de/lernen/")))check(manifestRedirects.has(redirectKey(redirect)),`${redirect.source}: Vercel content redirect missing from route manifest`);
const pageFile=route=>route==="/"?join(dist,"index.html"):join(dist,route.replace(/^\//,""),"index.html");const htmls=new Map();const titles=new Map();const descriptions=new Map();
for(const route of [...indexable,...noindex]){try{const html=await readFile(pageFile(route),"utf8");htmls.set(route,html);const canonical=route==="/"?`${host}/`:`${host}${route}`;check(html.includes(`rel="canonical" href="${canonical}"`),`${route}: canonical`);check((html.match(/<h1\b/gi)??[]).length===1,`${route}: one h1`);check(html.includes("<main"),`${route}: main landmark`);check(noindex.includes(route)?html.includes('content="noindex, follow"'):!html.includes('<meta name="robots"'),`${route}: robots state`);const title=html.match(/<title>([^<]+)/)?.[1],description=html.match(/<meta name="description" content="([^"]+)/)?.[1];check(Boolean(title),`${route}: title`);check(Boolean(description),`${route}: description`);if(title){check(!titles.has(title),`${route}: duplicate title ${titles.get(title)}`);titles.set(title,route)}if(description){check(!descriptions.has(description),`${route}: duplicate description ${descriptions.get(description)}`);descriptions.set(description,route)}}catch{failures.push(`${route}: missing build file`)}}
for(const route of sitemapRoutes.filter(item=>item.lang==="en"&&item.alternates)){const a=route.alternates.en,b=route.alternates.de,ah=htmls.get(a)??"",bh=htmls.get(b)??"";check(ah.includes(`hreflang="de" href="${canonicalUrlForPath(b)}"`),`${a}: de hreflang`);check(bh.includes(`hreflang="en" href="${canonicalUrlForPath(a)}"`),`${b}: en hreflang`);check(ah.includes(`hreflang="x-default" href="${canonicalUrlForPath(a)}"`),`${a}: x-default hreflang`)}
const home=htmls.get("/")??"",homeDe=htmls.get("/de")??"";check(home.includes("Free AI Query Fanout Tool"),"English homepage thesis");check(homeDe.includes("Kostenloses AI Query Fanout Tool"),"German homepage thesis");check(home.includes("No signup · 20 runs in 24 hours")&&homeDe.includes("Ohne Anmeldung · 20 Läufe in 24 Stunden"),"homepage free-tool proof");check(home.includes('<meta property="og:title" content="Free AI Query Fanout Tool: OpenAI &amp; Gemini — ai-fanout.com"')&&home.includes('<meta property="og:image:alt"'),"English social metadata");check(homeDe.includes('<meta property="og:title" content="AI Query Fanout Tool: OpenAI &amp; Gemini — ai-fanout.com"')&&homeDe.includes('<meta property="og:locale" content="de_DE"'),"German social metadata");check(home.includes('<link rel="icon" type="image/webp" href="/brand/ai-fanout-logo.webp">'),"WebP favicon missing");for(const stale of ["Evidence Lab","Protocol Builder","Compare Answers","Want to compare AI answers?"])check(!home.includes(stale)&&!homeDe.includes(stale),`homepage stale concept: ${stale}`);check(home.includes('data-fanout-planner')&&home.includes('data-enabled="false"'),"tool must be present and fail closed in default build");
const privacy=htmls.get("/datenschutz")??"";for(const claim of ["OpenRouter","OpenAI","Google Gemini","Cloudflare Turnstile","zwanzig Versuchen","Umami-Nutzungsanalyse","Nicht an Umami übermittelt","keine Keywordtexte","höchstens 24 Monate","jährlich überprüft","hilfreich"])check(privacy.includes(claim),`privacy missing: ${claim}`);for(const html of htmls.values()){check(html.includes('src="https://analytics.contextter.com/script.js"'),"Umami script missing");check(html.includes('data-domains="ai-fanout.com,www.ai-fanout.com"')&&html.includes('data-do-not-track="true"')&&html.includes('data-exclude-search="true"')&&html.includes('data-exclude-hash="true"'),"Umami privacy configuration missing")}
const sitemap=await readFile(join(dist,"sitemap.xml"),"utf8"),stylesheet=await readFile(join(dist,"sitemap.xsl"),"utf8"),robots=await readFile(join(dist,"robots.txt"),"utf8");
check(sitemap.includes('<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>')&&stylesheet.includes('count(s:urlset/s:url)'),"human-readable sitemap stylesheet missing");check(sitemap.includes('xmlns:xhtml="http://www.w3.org/1999/xhtml"'),"sitemap missing xhtml namespace");for(const namespace of ["xmlns:news=","xmlns:image=","xmlns:video="])check(!sitemap.includes(namespace),`sitemap contains unused namespace ${namespace}`);
const sitemapItems=[...sitemap.matchAll(/<url>([\s\S]*?)<\/url>/g)].map(match=>{const block=match[1],loc=block.match(/<loc>([^<]+)<\/loc>/)?.[1],lastmod=block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1],links=[...block.matchAll(/<xhtml:link\b([^>]+?)\/?>(?:<\/xhtml:link>)?/g)].map(link=>({lang:link[1].match(/hreflang="([^"]+)"/)?.[1],url:link[1].match(/href="([^"]+)"/)?.[1]}));return{loc,lastmod,links}});
check(sitemapItems.length===sitemapRoutes.length,`sitemap entry count ${sitemapItems.length} does not match registry ${sitemapRoutes.length}`);
const normalizeUrl=url=>{const parsed=new URL(url);return parsed.pathname==="/"?`${parsed.origin}/`:url};
const actualUrls=new Set(sitemapItems.map(item=>normalizeUrl(item.loc)));for(const route of sitemapRoutes){const expectedUrl=canonicalUrlForPath(route.path),item=sitemapItems.find(candidate=>normalizeUrl(candidate.loc)===expectedUrl);check(Boolean(item),`sitemap missing ${route.path}`);if(!item)continue;const actualDate=item.lastmod?.slice(0,10);check(actualDate===route.lastmod,`${route.path}: lastmod ${item.lastmod} does not match ${route.lastmod}`);check(Number.isFinite(Date.parse(item.lastmod))&&Date.parse(item.lastmod)<=Date.now()+86_400_000,`${route.path}: lastmod is invalid or in the future`);const expectedLinks=route.alternates?Object.entries(route.alternates).map(([lang,path])=>`${lang}|${canonicalUrlForPath(path)}`).sort():[],actualLinks=item.links.map(link=>`${link.lang}|${normalizeUrl(link.url)}`).sort();check(JSON.stringify(actualLinks)===JSON.stringify(expectedLinks),`${route.path}: sitemap hreflang mismatch`)}for(const url of actualUrls){const path=new URL(url).pathname.replace(/\/$/,"")||"/";check(sitemapRouteByPath.has(path),`sitemap contains unregistered URL ${url}`)}for(const route of noindex)check(!actualUrls.has(canonicalUrlForPath(route)),`sitemap leaked ${route}`);check(robots.includes("Allow: /")&&robots.includes("Sitemap: https://ai-fanout.com/sitemap.xml")&&!robots.includes("Disallow: /"),"robots policy");
for(const route of sitemapRoutes.filter(item=>item.role==="guide")){const html=htmls.get(route.path)??"",toolHref=route.lang==="de"?"/de#tool":"/#tool";check(html.includes('class="article-tool-cta"'),`${route.path}: contextual tool CTA missing`);check(html.includes(`href="${toolHref}"`),`${route.path}: contextual tool CTA target`);check(html.includes('"@type":"TechArticle"')&&html.includes('"@type":"BreadcrumbList"'),`${route.path}: article and breadcrumb structured data`);check(html.includes('"logo":{"@type":"ImageObject","url":"https://ai-fanout.com/brand/ai-fanout-logo.webp","width":512,"height":512}'),`${route.path}: publisher logo structured data`)}
const longtailChecks=[
  ["/library/what-is-ai-query-fanout",["Does Google AI Mode use query fan-out?","Is query fanout the same as keyword expansion?"]],
  ["/library/how-to-see-openai-search-queries",["Does ChatGPT Search rewrite a prompt into targeted searches?","Can the OpenAI API expose the actual search queries from one run?","https://help.openai.com/en/articles/9237897"]],
  ["/library/ai-citations",["What is a ChatGPT citation?","What is a Gemini citation?"]],
  ["/library/seo-for-ai-search",["Does traditional SEO still matter for AI search?","How should I use long-tail fanout queries?"]],
  ["/de/lernen/was-ist-ai-query-fanout",["Nutzt Google AI Mode Query Fan-Out?","Ist Query Fanout dasselbe wie Keyword-Erweiterung?"]],
  ["/de/lernen/openai-suchanfragen-sehen",["Formuliert ChatGPT Search eine Eingabe in gezielte Suchen um?","Kann die OpenAI API die tatsächlichen Suchqueries eines Laufs offenlegen?"]],
];
for(const [route,needles] of longtailChecks){const html=htmls.get(route)??"";for(const needle of needles)check(html.includes(needle),`${route}: missing longtail answer or source ${needle}`)}
const routeExists=async path=>{if(path==="/"||[...indexable,...noindex,"/robots.txt","/sitemap.xml","/sitemap.xsl"].includes(path))return true;try{if(path.startsWith("/_astro/")||path.startsWith("/brand/")||path.startsWith("/examples/")||path.startsWith("/contracts/")){await access(join(dist,path.slice(1)));return true}await access(pageFile(path));return true}catch{return false}};for(const [route,html] of htmls)for(const match of html.matchAll(/href="([^"]+)"/g)){const href=match[1];if(!href.startsWith("/")||href.startsWith("//"))continue;const path=href.split(/[?#]/)[0];if(path)check(await routeExists(path),`${route}: broken link ${href}`)}
const all=[...htmls.values()].join("\n").toLowerCase();for(const claim of ["reveals chain of thought","accesses private retrieval traces","guaranteed rankings","independently verified by contextter"])check(!all.includes(claim),`forbidden claim: ${claim}`);
const server=await preview({root,logLevel:"silent",server:{host:"127.0.0.1",port:0}});try{for(const route of [...indexable,...noindex,"/robots.txt","/sitemap.xml","/sitemap.xsl"]){const requestPath=route!=="/"?route.replace(/\/$/,""):route;const response=await fetch(`http://${server.host}:${server.port}${requestPath}`,{redirect:"manual"});check(response.status===200,`${route}: HTTP ${response.status}`)}for(const route of [...retired,"/not-a-real-page"]){const response=await fetch(`http://${server.host}:${server.port}${route}`,{redirect:"manual"});check(response.status===404&&!response.headers.has("location"),`${route}: real 404`)} }finally{await server.stop()}
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log(`QA passed: ${indexable.length} indexable pages, ${noindex.length} noindex route and ${retired.length} retired 404 routes, bilingual hreflang, sitemap, robots and links.`);
